name: my_fixed_app

description: Flutter rewrite of the Gazavba messaging experience with native performance and robust API integrations.
publish_to: 'none'
version: 1.0.0+1


environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.5.1
  dio: ^5.4.3+1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3
  go_router: ^14.2.3
  socket_io_client: ^2.0.3+1
  intl: ^0.19.0
  animations: ^2.0.8
  logging: ^1.2.0
  collection: ^1.18.0
  image_picker: ^1.0.7
  http_parser: ^4.0.2
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.10
flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/logo.jpg
flutter_native_splash:
  color: "#ffffff"           # background color while starting
  image: assets/images/logo.jpg
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo.jpg"
  image_path: "assets/images/logo.jpg"
