include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_final_locals: true
    prefer_single_quotes: true
    use_full_hex_values_for_flutter_colors: true
    always_use_package_imports: true
    avoid_print: true
